name: fl_writer
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_quill: ^11.4.0 # Updated flutter_quill version
  google_generative_ai: ^0.4.2 # Added google_generative_ai
  shared_preferences: ^2.2.2 # Added shared_preferences

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true 